services:
  app:
    container_name: socialmedia-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
  postgres:
    container_name: socialmedia_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    image: postgres:15.2-alpine
  minio:
    container_name: scialmedia_minio
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/minio:/data
    env_file:
      - .env
    command: server ~/data --console-address :9001
