spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWRD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret_key: ${JWT_SECRET_KEY}
springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs/